# Welcome to Jekyll!

title: Barbara Togander
email: web.togander@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Test site for artist Barbara Togander.

domain: barbaratogander.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://barbaratogander.com  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""    # place folder name if the site is served in a subfolder
permalink: pretty
